### ISSUE TITLE
Crash on quick saving (F6)

### ISSUE THREAD

**Issue by q4a** [storm-devs/storm-engine#9]
I tested on `develop` branch with `clang-debug` config. This commit: https://github.com/storm-devs/storm-engine/commit/808dbb4019c9da4ddd224a7b670c12d848f29992
Step to reproduce:
- start new game;
- talk to the first guard who will lead you forward;
- then do 2-5 quick save (F6).

The error is floating. It appears more often if you load this save and then do 2-5 quick save (F6).
[save.zip](https://github.com/storm-devs/storm-engine/files/6197332/save.zip)

![error](https://user-images.githubusercontent.com/1950719/112313914-73870900-8cb9-11eb-93b0-f775f50e8bfc.png)

**Comment by np-c0mp1ete** [comment]
Ah, I remember @ugeen4 reported this issue some time ago. Here's a link to a crash dump + pdb he got back then. https://yadi.sk/d/9VxdvBYjvoEkaQ

**Comment by espkk** [comment]
> Ah, I remember @ugeen4 reported this issue some time ago. Here's a link to a crash dump + pdb he got back then. https://yadi.sk/d/9VxdvBYjvoEkaQ

Do you also have hash of the related commit?

**Comment by espkk** [comment]
The particular problem is around reload_locator_ref (reload.c) pointing to non-existing attributes instance.
I fixed it in my CoAS branch replacing aref with object and doing:
`CopyAttributes(&reload_locator_ref, GetAttributeN(reload_group, i));`
instead of
`reload_locator_ref = GetAttributeN(reload_group, i);`

I cannot say for now if this is indeed the engine issue (should referenced attributes instance be available?) or scripts problem that was hidden for years. 
This needs more investigation
